language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kunal-kp/travis-ci-test -f Dockerfile.dev .

script:
  - docker run -e CI=true kunal-kp/travis-ci-test npm run test
